AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'config/**/*'
    - 'config.ru'
    - 'spec/spec_helper.rb'

IndentationWidth:
  Enabled: false
Style/Tab:
  Enabled: false
TrailingBlankLines:
  Enabled: false